apps/omg_performance/
apps/omg/test
apps/omg_eth/test

apps/omg/lib/omg/utxo/position.ex:46: Type specification 'Elixir.OMG.Utxo.Position':'decode!'(number()) -> t() is a supertype of the success typing: 'Elixir.OMG.Utxo.Position':'decode!'(number()) -> {'utxo_position',non_neg_integer(),non_neg_integer(),char()}
apps/omg/lib/omg/utxo/position.ex:52: Type specification 'Elixir.OMG.Utxo.Position':decode(number()) -> {'ok',t()} | {'error','encoded_utxo_position_too_low'} is a supertype of the success typing: 'Elixir.OMG.Utxo.Position':decode(number()) -> {'error','encoded_utxo_position_too_low'} | {'ok',{'utxo_position',non_neg_integer(),non_neg_integer(),char()}}
apps/omg/lib/omg/utxo/position.ex:76: Type specification 'Elixir.OMG.Utxo.Position':get_position(pos_integer()) -> {non_neg_integer(),non_neg_integer(),non_neg_integer()} is a supertype of the success typing: 'Elixir.OMG.Utxo.Position':get_position(pos_integer()) -> {non_neg_integer(),non_neg_integer(),char()}
apps/omg_child_chain_rpc/lib/omg_child_chain_rpc/web/endpoint.ex:15: Expression produces a value of type 'error' | 'excluded' | 'ignored' | 'unsampled' | {'ok',binary() | pid() | #{'__struct__':='Elixir.Task', 'owner':='nil' | pid(), 'pid':='nil' | pid(), 'ref':='nil' | reference()}}, but this value is unmatched
apps/omg_watcher_rpc/lib/web/endpoint.ex:15: Expression produces a value of type 'error' | 'excluded' | 'ignored' | 'unsampled' | {'ok',binary() | pid() | #{'__struct__':='Elixir.Task', 'owner':='nil' | pid(), 'pid':='nil' | pid(), 'ref':='nil' | reference()}}, but this value is unmatched
lib/phoenix/router.ex:316: The pattern 'error' can never match the type {#{'conn':='nil', 'log':='debug', 'path_params':=map(), 'pipe_through':=[any(),...], 'plug':='Elixir.OMG.ChildChainRPC.Web.Controller.Block' | 'Elixir.OMG.ChildChainRPC.Web.Controller.Fallback' | 'Elixir.OMG.ChildChainRPC.Web.Controller.Transaction', 'plug_opts':='Elixir.Route.NotFound' | 'get_block' | 'submit', 'route':=<<_:48,_:_*8>>},fun((_,map()) -> any()),fun((_) -> map()),{'Elixir.OMG.ChildChainRPC.Web.Controller.Block','get_block'} | {'Elixir.OMG.ChildChainRPC.Web.Controller.Fallback','Elixir.Route.NotFound'} | {'Elixir.OMG.ChildChainRPC.Web.Controller.Transaction','submit'}}
lib/phoenix/router.ex:316: The pattern 'error' can never match the type {#{'conn':='nil', 'log':='debug', 'path_params':=map(), 'pipe_through':=[any(),...], 'plug':='Elixir.OMG.WatcherRPC.Web.Controller.Account' | 'Elixir.OMG.WatcherRPC.Web.Controller.Alarm' | 'Elixir.OMG.WatcherRPC.Web.Controller.Challenge' | 'Elixir.OMG.WatcherRPC.Web.Controller.Fallback' | 'Elixir.OMG.WatcherRPC.Web.Controller.InFlightExit' | 'Elixir.OMG.WatcherRPC.Web.Controller.Status' | 'Elixir.OMG.WatcherRPC.Web.Controller.Transaction' | 'Elixir.OMG.WatcherRPC.Web.Controller.Utxo', 'plug_opts':=atom(), 'route':=<<_:48,_:_*8>>},fun((_,map()) -> any()),fun((_) -> map()),{'Elixir.OMG.WatcherRPC.Web.Controller.Account' | 'Elixir.OMG.WatcherRPC.Web.Controller.Alarm' | 'Elixir.OMG.WatcherRPC.Web.Controller.Challenge' | 'Elixir.OMG.WatcherRPC.Web.Controller.Fallback' | 'Elixir.OMG.WatcherRPC.Web.Controller.InFlightExit' | 'Elixir.OMG.WatcherRPC.Web.Controller.Status' | 'Elixir.OMG.WatcherRPC.Web.Controller.Transaction' | 'Elixir.OMG.WatcherRPC.Web.Controller.Utxo',atom()}}
lib/websockex.ex:19: Function handle_cast/2 only terminates with explicit exception
lib/websockex.ex:297: Expression produces a value of type 'ok' | {'error',_}, but this value is unmatched
